title: GeoData
description: GeoData is an online platform for geospatial data discovery at UCLA. GeoData is built upon GeoBlacklight. 
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Jamie Jamison & Zhiyuan Yao
repo_url: 'https://github.com/zyykyy/data-science-center-termsofuse'
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
